#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker { image 'maven' }
            }
            steps {
                sh "java -version"
                sh "mvn --version"
                sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}
